load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "sdk",
    srcs = ["sdk.go"],
    importpath = "originlang/host/sdk",
    visibility = ["//visibility:public"],
    deps = [
        "//src/go/host/plugin",
        "//src/go/host/rpc",
        "//src/go/host/transport",
        "//src/go/host/transport/stdio",
    ],
)
