load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "hostd",
    srcs = ["main.go"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/go/host/manager",
        "//src/go/host/plugin",
        "//src/go/host/rpc",
        "//src/go/host/transport",
        "//src/go/host/transport/stdio",
        "//src/go/host/transport/tcp",
    ],
)
